apiVersion: 1

datasources:
  - name: Pulse Postgres
    uid: pulse-postgres
    type: postgres
    access: proxy
    url: db:5432
    user: ${DB_USER}
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      database: ${DB_NAME}
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: false
